version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        build: ./docker/database
        environment:
            SA_PASSWORD: "L@rc0mb3"
            ACCEPT_EULA: "Y"