version: "3"
services:
    db:
        build: ./docker/database
        environment:
            SA_PASSWORD: "L@rc0mb3"
            ACCEPT_EULA: "Y"
    web:        image: "gcr.io/headhunterreviews-ffb31/feltonvillain/headhuntapi"        ports:           - "5000:80"        depends_on:           - db     site:        image: "gcr.io/headhunterreviews-ffb31/feltonvillain/headhuntreview"        ports:           - "4200:80"        depends_on:           - db