apiVersion: v1
kind: Service
metadata:
  name: headhunterreviews-ffb31
  labels:
    run: headhunterreviews-ffb31
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: headhunterreviews-ffb31