version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/aspnetcore-build:2.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore headhuntapi.csproj /p:StartupObject=headhuntapi.Program
      - run: dotnet build headhuntapi.csproj /p:StartupObject=headhuntapi.Program
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=headhuntapi -t headhuntapi .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/headhuntapi.tar headhuntapi
      - deploy:
          name: Push Application Docker Image           command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker tag headhuntapi "$DOCKER_USER/headhuntapi:${CIRCLE_SHA1}"               docker push "$DOCKER_USER/headhuntapi:${CIRCLE_SHA1}"
            fi
