version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-master-1
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=headhuntapi -t headhuntapi .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/headhuntapi.tar app
      - save_cache:
          key: v1-master-1
          paths:
            - /caches/headhuntapi.tar
      - run: dotnet restore headhuntapi.csproj /p:StartupObject=headhuntapi.Program
      - run: dotnet build headhuntapi.csproj /p:StartupObject=headhuntapi.Program
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=headhuntapi -t headhuntapi .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/headhuntapi.tar headhuntapi
      - deploy:
          name: Push Application Docker Image           command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker tag headhuntapi "$DOCKER_USER/headhuntapi:${CIRCLE_SHA1}"               docker push "$DOCKER_USER/headhuntapi:${CIRCLE_SHA1}"
            fi
