using System; using System.Collections.Generic; using System.Linq; using System.Threading.Tasks; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.Authorization; using headhuntapi.Models; using headhuntapi.Services; using headhuntapi.Models.Dtos; using headhuntapi.Filters;

namespace headhuntapi.Controllers
{     [Route("api/[controller]")]
    public class RecruiterController : Controller
    {
        private readonly IRecruiterRepository _recruiterRepo;         private readonly ICompanyRepository _companyRepo;          public RecruiterController(IRecruiterRepository recruiterRepo, ICompanyRepository companyRepo)         {             _recruiterRepo = recruiterRepo;             _companyRepo = companyRepo;         }          [HttpGet]         [Authorize]         public JsonResult Get()         {             var recruiters = _recruiterRepo.GetRecruiters();             return Json(recruiters);         }          [HttpGet("{id}")]         [Authorize]         public JsonResult Get(Guid id)         {             var recruiter = _recruiterRepo.GetRecruiter(id);             return Json(recruiter);         }          // POST api/values         [HttpPost]         //[Authorize]         [Throttle(Name = "ThrottleTest", Seconds = 5)]         public JsonResult Post([FromBody] RecruiterDto recruiter)         {              var company = _companyRepo.GetCompany(recruiter.CompanyId);             if (company == null)             {                 return Json(false);             }             Recruiters recruiteF = new Recruiters
            {
                Name = recruiter.Name,
                Title = recruiter.Title,                 LinkedIn = recruiter.LinkedIn,                 Email = recruiter.Email,                 Level = recruiter.Level,                 CompanyId = company.Id,                 UniqueId = System.Guid.NewGuid()             };              _recruiterRepo.AddRecruiter(recruiteF);             return Json(true);         }          [HttpPut("{id}")]         [Authorize]         [Throttle(Name = "ThrottleTest", Seconds = 5)]         public IActionResult Update(Guid id, [FromBody] RecruiterDto recruiter)         {             var recruiterUpdate = _recruiterRepo.GetRecruiter(id);             if (recruiterUpdate == null)             {                 return NotFound();             }             recruiterUpdate.Name = recruiter.Name;             recruiterUpdate.Title = recruiter.Title;             recruiterUpdate.LinkedIn = recruiter.LinkedIn;             recruiterUpdate.Email = recruiter.Email;             recruiterUpdate.Level = recruiter.Level;             recruiterUpdate.IsApproved = Convert.ToByte(recruiter.IsApproved);              _recruiterRepo.UpdateRecruiter(recruiterUpdate);             return new NoContentResult();         }           // DELETE api/values/5         [HttpDelete("{id}")]         [Authorize]         public JsonResult Delete(Guid id)         {             _recruiterRepo.DeleteRecruiter(id);             return Json(true);         }
    }
}
