FROM microsoft/mssql-server-linux:latest

#COPY ./import-data.sh /usr/local/bin/
#COPY ./setup.sql /usr/local/bin/

#RUN chmod +x /usr/local/bin/import-data.sh \
#chmod +x /usr/local/bin/setup.sql

#CMD ["/usr/local/bin/import-data.sh"]